### ISSUE TITLE
[BUG] - Plus d'update de la Linky card

### ISSUE THREAD

**Issue by HermesHonshappo** [m4dm4rtig4n/myelectricaldata#161]
**Description du bug**
Après avoir migré en version 0.8.3-dev ce matin, j'ai fini par désactiver MQTT et InfluxDB pour éviter les plantages.
L'add-on s'est donc bien lancé, mais j'ai remarqué qu'il ne mettait pas à jour la carte Linky. D'ailleurs, je ne vois plus l'option dans la doc. 
C'était ça dans mon config.yaml de l'ancienne version de l'add-on. Je l'avais laissé dans le fichier de conf.
```
home_assistant:
  card_myenedis: true
```

Je précise que j'avais MQTT, InfluxDB et le auto-discovery désactivés.  J'ai  refait l'essai en activant MQTT, mais sans succès, la carte de se met pas à jour.

Une fois le fallback fait en 0.7.7.3 et relancé l'add-on, la carte Linky se met de nouveau a jour.

**Configuration**

```
myelectricaldata:
  "MONPDL":
    enable: 'true'
    token: 'MONTOKEN'
    name: "MAMAISON"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1658'
    consumption_price_hc: '0.1401'
    consumption_price_hp: '0.1754'
#    consumption_max_date: "2021-06-01"
#    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: 01H56-6H56;13H56-16H56 # LUNDI
    offpeak_hours_1: 01H56-6H56;13H56-16H56 # MARDI
    offpeak_hours_2: 01H56-6H56;13H56-16H56 # MERCREDI
    offpeak_hours_3: 01H56-6H56;13H56-16H56 # JEUDI
    offpeak_hours_4: 01H56-6H56;13H56-16H56 # VENDREDI
    offpeak_hours_5: 01H56-6H56;13H56-16H56 # SAMEDI
    offpeak_hours_6: 01H56-6H56;13H56-16H56 # DIMANCHE
#    activation_date_detail: "2021-06-05"
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'
```
**Type d'installation**
HassIO sur mini-PC

**Version : 0.8.3-dev**
