### ISSUE TITLE
[BUG] - Souci sur le calcul HP/HC

### ISSUE THREAD

**Issue by Jeoffreybauvin** [m4dm4rtig4n/myelectricaldata#165]
**Description du bug**

Il y a un souci sur le calcul des HC/HP : 

Le mercredi je suis censé etre en full heure creuse. Pour autant, dans sqlite3 j'ai que des HP...

```
sqlite> select * from consumption_detail where date > "2022-11-30 00:00:00.000000" and date < "2022-12-01 00:00:00.000000" and measure_type="HP";
34945|05192908731636|2022-11-30 00:15:00.000000|236|15|HP|0|0
34946|05192908731636|2022-11-30 00:30:00.000000|260|15|HP|0|0
34947|05192908731636|2022-11-30 00:45:00.000000|212|15|HP|0|0
34948|05192908731636|2022-11-30 01:00:00.000000|316|15|HP|0|0
....
35039|05192908731636|2022-11-30 23:45:00.000000|608|15|HP|0|0

sqlite> select * from consumption_detail where date > "2022-11-30 00:00:00.000000" and date < "2022-12-01 00:00:00.000000" and measure_type="HC";
sqlite> 
```

**Configuration**

```
myelectricaldata:
  "POUET":              # Replace XXXXXXXXXXXXXX by your PDL Number. MANDATORY
    addresses: true
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.2103'
    consumption_price_hc: '0.1499'
    consumption_price_hp: '0.2103'
    name: Maison
    offpeak_hours_0: 3H40-8h10;12H40-16H10
    offpeak_hours_1: 3H40-8h10;12H40-16H10
    offpeak_hours_2: 0H00-0H00
    offpeak_hours_3: 3H40-8h10;12H40-16H10
    offpeak_hours_4: 3H40-8h10;12H40-16H10
    offpeak_hours_5: 0H00-0H00
    offpeak_hours_6: 0H00-0H00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: "POUET"
```

Le mercredi et le weekend, je suis full HC. 

**Type d'installation**
Docker

**Version : 0.8.4**
