### ISSUE TITLE
[BUG] - Incohérence sur le total HP + HC

### ISSUE THREAD

**Issue by JbPasquier** [m4dm4rtig4n/myelectricaldata#200]
**Description du bug**
Si je renseigne `consumption_price_base` (config.yaml) à `0` alors tous les `dailyweek_cost` (mqtt) sont à zéro.
Si je renseigne une valeur, alors la somme de `dailyweek_costHC` et de `dailyweek_costHP` n'est pas égale à `dailyweek_cost`.

**Configuration**
```yaml
cycle: 14400
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: redacted
  port: redacted
  token: redacted
  org: redacted
  bucket: redacted
  method: asynchronous
mqtt:
  enable: true
  hostname: redacted
  port: redacted
  username: redacted
  password: redacted
  prefix: redacted
  client_id: redacted
  retain: true
  qos: 0
myelectricaldata:
  "redacted":
    enable: 'true'
    token: redacted
    name: "redacted"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0'
    consumption_price_hc: '0.0862'
    consumption_price_hp: '0.1272'
    consumption_max_date: "redacted"
    consumption_detail_max_date: "redacted"
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "redacted"
    production_detail_max_date: "redacted"
    refresh_addresse: 'false'
    refresh_contract: 'false'
```

**Type d'installation**
Docker

**Version : latest**
