### ISSUE TITLE
[BUG] - ne remonte que des zéros

### ISSUE THREAD

**Issue by LGO44** [m4dm4rtig4n/myelectricaldata#268]
Myelectricaldata ne remonte que des zéro pour mes 2 compteurs depuis 3 jours
logs:
2023-01-09 09:43:30.423 -     INFO :   => 0
2023-01-09 09:43:30.424 -     INFO :  last_month
2023-01-09 09:43:30.429 -     INFO :   => 0
2023-01-09 09:43:30.430 -     INFO :  current_month
2023-01-09 09:43:30.435 -     INFO :   => 0
2023-01-09 09:43:30.436 -     INFO :  current_month_last_year
2023-01-09 09:43:30.441 -     INFO :   => 0
2023-01-09 09:43:30.442 -     INFO :  last_month_last_year
2023-01-09 09:43:30.447 -     INFO :   => 0
2023-01-09 09:43:30.447 -     INFO :  current_year
2023-01-09 09:43:30.454 -     INFO :   => 0
2023-01-09 09:43:30.455 -     INFO :  current_year_last_year
2023-01-09 09:43:30.460 -     INFO :   => 0
2023-01-09 09:43:30.461 -     INFO :  last_year
2023-01-09 09:43:30.465 -     INFO :   => 0
2023-01-09 09:43:30.466 -     INFO :  yesterday_hp / yesterday_hc
2023-01-09 09:43:30.471 -     INFO :   => HC : 0
2023-01-09 09:43:30.472 -     INFO :   => HP : 0
2023-01-09 09:43:30.473 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2023-01-09 09:43:30.478 -     INFO :   => 0
2023-01-09 09:43:30.479 -     INFO :  current_week_evolution
2023-01-09 09:43:30.480 -     INFO :   => 0
2023-01-09 09:43:30.481 -     INFO :  current_month_evolution
2023-01-09 09:43:30.482 -     INFO :   => 0
2023-01-09 09:43:30.482 -     INFO :  yesterday_evolution
2023-01-09 09:43:30.483 -     INFO :  yesterday
2023-01-09 09:43:30.488 -     INFO :   => 0
2023-01-09 09:43:30.488 -     INFO :  yesterday_1
2023-01-09 09:43:30.493 -     INFO :   => 0
2023-01-09 09:43:30.494 -     INFO :   => 0
2023-01-09 09:43:30.494 -     INFO :  monthly_evolution
2023-01-09 09:43:30.495 -     INFO :  last_month
2023-01-09 09:43:30.504 -     INFO :   => 0
2023-01-09 09:43:30.507 -     INFO :  last_month_last_year
2023-01-09 09:43:30.516 -     INFO :   => 0
2023-01-09 09:43:30.517 -     INFO :   => 0
2023-01-09 09:43:30.985 -     INFO :  current_week
2023-01-09 09:43:30.995 -     INFO :   => 0
2023-01-09 09:43:31.000 -     INFO :  last_week
2023-01-09 09:43:31.010 -     INFO :   => 0
2023-01-09 09:43:31.010 -     INFO :  current_week_last_year
2023-01-09 09:43:31.020 -     INFO :   => 0
2023-01-09 09:43:31.020 -     INFO :  last_month
2023-01-09 09:43:31.028 -     INFO :   => 0
2023-01-09 09:43:31.032 -     INFO :  current_month
2023-01-09 09:43:31.041 -     INFO :   => 0
2023-01-09 09:43:31.041 -     INFO :  current_month_last_year
2023-01-09 09:43:31.051 -     INFO :   => 0
2023-01-09 09:43:31.051 -     INFO :  last_month_last_year
2023-01-09 09:43:31.058 -     INFO :   => 0
2023-01-09 09:43:31.059 -     INFO :  current_year
2023-01-09 09:43:31.064 -     INFO :   => 0
2023-01-09 09:43:31.064 -     INFO :  current_year_last_year
2023-01-09 09:43:31.075 -     INFO :   => 0
2023-01-09 09:43:31.077 -     INFO :  last_year
2023-01-09 09:43:31.082 -     INFO :   => 0
2023-01-09 09:43:31.083 -     INFO :  yesterday_hp / yesterday_hc
2023-01-09 09:43:31.089 -     INFO :   => HC : 0
2023-01-09 09:43:31.089 -     INFO :   => HP : 0
2023-01-09 09:43:31.090 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2023-01-09 09:43:31.095 -     INFO :   => 0
2023-01-09 09:43:31.096 -     INFO :  current_week_evolution
2023-01-09 09:43:31.097 -     INFO :   => 0
2023-01-09 09:43:31.097 -     INFO :  current_month_evolution
2023-01-09 09:43:31.098 -     INFO :   => 0
2023-01-09 09:43:31.099 -     INFO :  yesterday_evolution
2023-01-09 09:43:31.099 -     INFO :  yesterday
2023-01-09 09:43:31.111 -     INFO :   => 0
2023-01-09 09:43:31.112 -     INFO :  yesterday_1
2023-01-09 09:43:31.124 -     INFO :   => 0
2023-01-09 09:43:31.126 -     INFO :   => 0
2023-01-09 09:43:31.127 -     INFO :  monthly_evolution
2023-01-09 09:43:31.128 -     INFO :  last_month
2023-01-09 09:43:31.136 -     INFO :   => 0
2023-01-09 09:43:31.137 -     INFO :  last_month_last_year
2023-01-09 09:43:31.142 -     INFO :   => 0
2023-01-09 09:43:31.143 -     INFO :   => 0
2023-01-09 09:43:31.584 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.590 -     INFO :  EXPORT TERMINÉ
2023-01-09 09:43:31.590 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.590 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.591 -     INFO :  EXPORTATION INFLUXDB
2023-01-09 09:43:31.591 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.591 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.591 -     INFO :  [14881765491878] EXPORTATION DES DONNÉES "CONSUMPTION" DANS INFLUXDB
2023-01-09 09:43:31.592 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.598 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.599 -     INFO :  [14881765491878] EXPORTATION DES DONNÉES "CONSUMPTION_DETAIL" DANS INFLUXDB
2023-01-09 09:43:31.600 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.605 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.606 -     INFO :  EXPORT TERMINÉ
2023-01-09 09:43:31.608 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.608 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 09:43:31.609 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2023-01-09 09:43:31.610 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2023-01-09 09:43:31.610 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2023-01-09 09:43:31.614 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2023-01-09 09:43:31.615 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2023-01-09 09:43:31.616 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2023-01-09 09:43:31.617 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Configuration**
cycle: 3600
debug: false
wipe_cache: false
wipe_influxdb: false
myelectricaldata:
  xxxxxxxxxx2639:
    addresses: true
    enable: true
    name: ""
    cache: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1871
    consumption_price_hc: 0.1470
    consumption_price_hp: 0.1871
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: 01h30-07h30;12h30-14h30
    offpeak_hours_1: 01h30-07h30;12h30-14h30
    offpeak_hours_2: 01h30-07h30;12h30-14h30
    offpeak_hours_3: 01h30-07h30;12h30-14h30
    offpeak_hours_4: 01h30-07h30;12h30-14h30
    offpeak_hours_5: 01h30-07h30;12h30-14h30
    offpeak_hours_6: 01h30-07h30;12h30-14h30
    plan: HP/HC
    production: false
    production_detail: false
    refresh_addresse: false
    refresh_contract: false
    token: xxxxxxxxxx
  xxxxxxxxxx4881765491878:
    addresses: true
    enable: true
    name: ""
    cache: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1871
    consumption_price_hc: 0.1470
    consumption_price_hp: 0.1871
    consumption_max_date: "2022-12-01"
    consumption_detail_max_date: "2022-12-01"
    offpeak_hours_0: 00h50-06h50;14h20-16h20
    offpeak_hours_1: 00h50-06h50;14h20-16h20
    offpeak_hours_2: 00h50-06h50;14h20-16h20
    offpeak_hours_3: 00h50-06h50;14h20-16h20
    offpeak_hours_4: 00h50-06h50;14h20-16h20
    offpeak_hours_5: 00h50-06h50;14h20-16h20
    offpeak_hours_6: 00h50-06h50;14h20-16h20
    plan: HP/HC
    production: false
    production_detail: false
    refresh_addresse: false
    refresh_contract: false
    token: xxxxxxxxxx
home_assistant:
  enable: true
#  card_myenedis: true
#  discovery: true
  discovery_prefix: homeassistant
mqtt:
  client_id: myelectricaldata
  hostname: x.x.x.27
  enable: true
  password: 'yyyyyyyyyyyyyyyyyyy'
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: 'homeassistant'
influxdb:
  enable: true
  hostname: x.x.x.27
  port: 8086
  token: "home_assistant:**********"
  org: "-"
  bucket: "myelectricaldata/autogen"
  method: asynchronous

**Type d'installation**
HassIO ?

**Version : 8.1.3-beta1**

**Comment by m4dm4rtig4n** [comment]
Est-ce que tu as bien de la donnée chez Enedis ?

**Comment by geobar78** [comment]
Slt tout pareil, ce qui est bizarre c'est que dans les attributs on dirait que pour lui on est tjrs le 7, Enedis a l'air ok car j'ai bien les données qui remontent avec le sensor de saniho qui passe par MED.

ActivationDate
16 août 2014 à 00:00:00
LastUpdate
7 janvier 2023 à 08:56:57
TimeLastCall
7 janvier 2023 à 08:56:57
YesterdayDate
6 janvier 2023
Yesterday
0
YesterdayLastYearDate
7 janvier 2022
YesterdayLastYear
0
Daily
0, 0, 0, 15.6, 20.14, 20.98, 28.87
Current week
85,6
Last week
152,21
Day 1
0
Day 2
0
Day 3
0
Day 4
15,6
Day 5
20,14
Day 6
20,98
Day 7
28,87
Current week last year
195,22
Last month
620,49
Current month
56,73
Current month last year
167,9
Last month last year
932,13
Last year
7 524,87
Current year
56,73
Current year last year
167,9
Dailyweek
2023-01-06, 2023-01-05, 2023-01-04, 2023-01-03, 2023-01-02, 2023-01-01, 2022-12-31
Dailyweek cost
0, 0, 0, 2.2, 2.9, 3, 4.2
Dailyweek costHP
0, 0, 0, 0.9, 1.5, 1.3, 2.7
Dailyweek HP
0, 0, 0, 5.23, 9.17, 7.63, 16.41
Daily cost
0
Yesterday HP cost
0
Yesterday HP
0
Day 1 HP
0
Day 2 HP
0
Day 3 HP
0
Day 4 HP
5 239
Day 5 HP
9 176
Day 6 HP
7 639
Day 7 HP
16 417
Dailyweek costHC
0, 0, 0, 1.3, 1.4, 1.7, 1.5
Dailyweek HC
0, 0, 0, 10.36, 10.96, 13.34, 12.45
Yesterday HC cost
0
Yesterday HC
0
Day 1 HC
0
Day 2 HC
0
Day 3 HC
0
Day 4 HC
10 369
Day 5 HC
10 967
Day 6 HC
13 347
Day 7 HC
12 454
Peak offpeak percent
-17,17
Monthly evolution
-33,43
Current week evolution
-43,76
Current month evolution
-66,21
Yesterday evolution
0
ErrorLastCall
ErrorLastCallInterne
Current week number
01
Offpeak hours enedis
Lundi (23H00-7H00);Mardi (23H00-7H00);Mercredi (23H00-7H00);Jeudi (23H00-7H00);Vendredi (23H00-7H00);Samedi (23H00-7H00);Dimanche (23H00-7H00);
Offpeak hours
- - - 23H00
- 7H00
- - - 23H00
- 7H00
- - - 23H00
- 7H00
- - - 23H00
- 7H00
- - - 23H00
- 7H00
- - - 23H00
- 7H00
- - - 23H00
- 7H00
Subscribed power
6 kVA

**Comment by LGO44** [comment]
# Est-ce que tu as bien de la donnée chez Enedis ?
    les données Enedis sont enfin arrivées 
![image](https://user-images.githubusercontent.com/95585425/211324323-ed16f480-3ae2-4baf-ac5d-560b579d05a7.png)


# Que disent les logs ? 
 Logs de myelectricaldata
2023-01-09 14:43:36.885 -     INFO :   => 0
2023-01-09 14:43:36.887 -     INFO :  last_month
2023-01-09 14:43:36.905 -     INFO :   => 0
2023-01-09 14:43:36.906 -     INFO :  current_month
2023-01-09 14:43:36.917 -     INFO :   => 0
2023-01-09 14:43:36.920 -     INFO :  current_month_last_year
2023-01-09 14:43:36.936 -     INFO :   => 0
2023-01-09 14:43:36.938 -     INFO :  last_month_last_year
2023-01-09 14:43:36.953 -     INFO :   => 0
2023-01-09 14:43:36.955 -     INFO :  current_year
2023-01-09 14:43:36.966 -     INFO :   => 0
2023-01-09 14:43:36.970 -     INFO :  current_year_last_year
2023-01-09 14:43:36.984 -     INFO :   => 0
2023-01-09 14:43:36.987 -     INFO :  last_year
2023-01-09 14:43:36.996 -     INFO :   => 0
2023-01-09 14:43:36.997 -     INFO :  yesterday_hp / yesterday_hc
2023-01-09 14:43:37.030 -     INFO :   => HC : 0
2023-01-09 14:43:37.031 -     INFO :   => HP : 0
2023-01-09 14:43:37.032 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2023-01-09 14:43:37.043 -     INFO :   => 0
2023-01-09 14:43:37.050 -     INFO :  current_week_evolution
2023-01-09 14:43:37.052 -     INFO :   => 0
2023-01-09 14:43:37.053 -     INFO :  current_month_evolution
2023-01-09 14:43:37.054 -     INFO :   => 0
2023-01-09 14:43:37.055 -     INFO :  yesterday_evolution
2023-01-09 14:43:37.056 -     INFO :  yesterday
2023-01-09 14:43:37.068 -     INFO :   => 0
2023-01-09 14:43:37.074 -     INFO :  yesterday_1
2023-01-09 14:43:37.084 -     INFO :   => 0
2023-01-09 14:43:37.086 -     INFO :   => 0
2023-01-09 14:43:37.087 -     INFO :  monthly_evolution
2023-01-09 14:43:37.088 -     INFO :  last_month
2023-01-09 14:43:37.103 -     INFO :   => 0
2023-01-09 14:43:37.105 -     INFO :  last_month_last_year
2023-01-09 14:43:37.117 -     INFO :   => 0
2023-01-09 14:43:37.129 -     INFO :   => 0
2023-01-09 14:43:38.268 -     INFO :  current_week
2023-01-09 14:43:38.310 -     INFO :   => 0
2023-01-09 14:43:38.318 -     INFO :  last_week
2023-01-09 14:43:38.364 -     INFO :   => 0
2023-01-09 14:43:38.367 -     INFO :  current_week_last_year
2023-01-09 14:43:38.384 -     INFO :   => 0
2023-01-09 14:43:38.386 -     INFO :  last_month
2023-01-09 14:43:38.400 -     INFO :   => 0
2023-01-09 14:43:38.402 -     INFO :  current_month
2023-01-09 14:43:38.415 -     INFO :   => 0
2023-01-09 14:43:38.422 -     INFO :  current_month_last_year
2023-01-09 14:43:38.436 -     INFO :   => 0
2023-01-09 14:43:38.439 -     INFO :  last_month_last_year
2023-01-09 14:43:38.454 -     INFO :   => 0
2023-01-09 14:43:38.456 -     INFO :  current_year
2023-01-09 14:43:38.469 -     INFO :   => 0
2023-01-09 14:43:38.470 -     INFO :  current_year_last_year
2023-01-09 14:43:38.479 -     INFO :   => 0
2023-01-09 14:43:38.482 -     INFO :  last_year
2023-01-09 14:43:38.496 -     INFO :   => 0
2023-01-09 14:43:38.498 -     INFO :  yesterday_hp / yesterday_hc
2023-01-09 14:43:38.510 -     INFO :   => HC : 0
2023-01-09 14:43:38.516 -     INFO :   => HP : 0
2023-01-09 14:43:38.518 -     INFO :  peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2023-01-09 14:43:38.524 -     INFO :   => 0
2023-01-09 14:43:38.529 -     INFO :  current_week_evolution
2023-01-09 14:43:38.530 -     INFO :   => 0
2023-01-09 14:43:38.531 -     INFO :  current_month_evolution
2023-01-09 14:43:38.532 -     INFO :   => 0
2023-01-09 14:43:38.532 -     INFO :  yesterday_evolution
2023-01-09 14:43:38.532 -     INFO :  yesterday
2023-01-09 14:43:38.549 -     INFO :   => 0
2023-01-09 14:43:38.550 -     INFO :  yesterday_1
2023-01-09 14:43:38.564 -     INFO :   => 0
2023-01-09 14:43:38.565 -     INFO :   => 0
2023-01-09 14:43:38.567 -     INFO :  monthly_evolution
2023-01-09 14:43:38.568 -     INFO :  last_month
2023-01-09 14:43:38.578 -     INFO :   => 0
2023-01-09 14:43:38.580 -     INFO :  last_month_last_year
2023-01-09 14:43:38.592 -     INFO :   => 0
2023-01-09 14:43:38.593 -     INFO :   => 0
2023-01-09 14:43:39.747 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.757 -     INFO :  EXPORT TERMINÉ
2023-01-09 14:43:39.758 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.758 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.758 -     INFO :  EXPORTATION INFLUXDB
2023-01-09 14:43:39.758 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.758 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.759 -     INFO :  [14881765491878] EXPORTATION DES DONNÉES "CONSUMPTION" DANS INFLUXDB
2023-01-09 14:43:39.759 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.792 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.796 -     INFO :  [14881765491878] EXPORTATION DES DONNÉES "CONSUMPTION_DETAIL" DANS INFLUXDB
2023-01-09 14:43:39.802 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.820 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.830 -     INFO :  EXPORT TERMINÉ
2023-01-09 14:43:39.833 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.836 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-09 14:43:39.837 -     INFO : ▌│█║▌║▌║       ___                                 _     _____  _         _       _      _  _  _       ║▌║▌║█│▌
2023-01-09 14:43:39.838 -     INFO : ▌│█║▌║▌║      |_ _| _ __ ___   _ __    ___   _ __ | |_  |  ___|(_) _ __  (_) ___ | |__  | || || |      ║▌║▌║█│▌
2023-01-09 14:43:39.840 -     INFO : ▌│█║▌║▌║       | | | '_ ` _ \ | '_ \  / _ \ | '__|| __| | |_   | || '_ \ | |/ __|| '_ \ | || || |      ║▌║▌║█│▌
2023-01-09 14:43:39.841 -     INFO : ▌│█║▌║▌║       | | | | | | | || |_) || (_) || |   | |_  |  _|  | || | | || |\__ \| | | ||_||_||_|      ║▌║▌║█│▌
2023-01-09 14:43:39.842 -     INFO : ▌│█║▌║▌║      |___||_| |_| |_|| .__/  \___/ |_|    \__| |_|    |_||_| |_||_||___/|_| |_|(_)(_)(_)      ║▌║▌║█│▌
2023-01-09 14:43:39.842 -     INFO : ▌│█║▌║▌║                      |_|                                                                      ║▌║▌║█│▌
2023-01-09 14:43:39.843 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


# ma configuration ( j'espère plus lisible?)

**Configuration**
cycle: 3600
debug: false
wipe_cache: false
wipe_influxdb: false

**myelectricaldata:**
  **xxxxxxxxxx2639:**                                                # domicile
    addresses: true
    enable: true
    name: ""
    cache: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1871
    consumption_price_hc: 0.1470
    consumption_price_hp: 0.1871
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: 01h30-07h30;12h30-14h30
    offpeak_hours_1: 01h30-07h30;12h30-14h30
    offpeak_hours_2: 01h30-07h30;12h30-14h30
    offpeak_hours_3: 01h30-07h30;12h30-14h30
    offpeak_hours_4: 01h30-07h30;12h30-14h30
    offpeak_hours_5: 01h30-07h30;12h30-14h30
    offpeak_hours_6: 01h30-07h30;12h30-14h30
    plan: HP/HC
    production: false
    production_detail: false
    refresh_addresse: false
    refresh_contract: false
    token: xxxxxxxxxx

  **xxxxxxxxxx4881765491878:**                              # second compteur
    addresses: true
    enable: true
    name: ""
    cache: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1871
    consumption_price_hc: 0.1470
    consumption_price_hp: 0.1871
    consumption_max_date: "2022-12-01"
    consumption_detail_max_date: "2022-12-01"
    offpeak_hours_0: 00h50-06h50;14h20-16h20
    offpeak_hours_1: 00h50-06h50;14h20-16h20
    offpeak_hours_2: 00h50-06h50;14h20-16h20
    offpeak_hours_3: 00h50-06h50;14h20-16h20
    offpeak_hours_4: 00h50-06h50;14h20-16h20
    offpeak_hours_5: 00h50-06h50;14h20-16h20
    offpeak_hours_6: 00h50-06h50;14h20-16h20
    plan: HP/HC
    production: false
    production_detail: false
    refresh_addresse: false
    refresh_contract: false
    token: xxxxxxxxxx

**home_assistant:**
  enable: true
  discovery_prefix: homeassistant

**mqtt:**
  client_id: myelectricaldata
  hostname: x.x.x.27
  enable: true
  password: 'yyyyyyyyyyyyyyyyyyy'
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: 'homeassistant'

**influxdb:**
  enable: true
  hostname: x.x.x.27
  port: 8086
  token: "home_assistant:**********"
  org: "-"
  bucket: "myelectricaldata/autogen"
  method: asynchronous

**Comment by valderaplets** [comment]
J'ai la même. Que des 0. Pas de message d'erreur ..

**Comment by geobar78** [comment]
Par contre j'ai l'impression que les datas sont sur myelectricaldata_consumption maintenant. j'ai bon ?

**Comment by valderaplets** [comment]
```yaml
numPDL: 'XXXXX'
activationDate: '2016-07-19 00:00:00'
lastUpdate: '2023-01-07 08:02:29'
timeLastCall: '2023-01-07 08:02:29'
yesterdayDate: '2023-01-06'
yesterday: 0
yesterdayLastYearDate: '2022-01-07'
yesterdayLastYear: 0
daily:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
current_week: 0
last_week: 53.19
day_1: 0
day_2: 0
day_3: 0
day_4: 0
day_5: 0
day_6: 0
day_7: 0
current_week_last_year: 63.11
last_month: 231.41
current_month: 0
current_month_last_year: 55.22
last_month_last_year: 228.95
last_year: 2372.24
current_year: 0
current_year_last_year: 55.22
dailyweek:
  - '2023-01-06'
  - '2023-01-05'
  - '2023-01-04'
  - '2023-01-03'
  - '2023-01-02'
  - '2023-01-01'
  - '2022-12-31'
dailyweek_cost:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
dailyweek_costHP:
  - 0
  - 1
  - 1.1
  - 1.7
  - 1.3
  - 1.4
  - 1.5
dailyweek_HP:
  - 0
  - 5.92
  - 6.28
  - 9.6
  - 7.19
  - 8.1
  - 8.65
daily_cost: 0
yesterday_HP_cost: 0
yesterday_HP: 0
day_1_HP: 0
day_2_HP: 5921
day_3_HP: 6284
day_4_HP: 9603
day_5_HP: 7190
day_6_HP: 8104
day_7_HP: 8655
dailyweek_costHC:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
dailyweek_HC:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
yesterday_HC_cost: 0
yesterday_HC: 0
day_1_HC: 0
day_2_HC: 0
day_3_HC: 0
day_4_HC: 0
day_5_HC: 0
day_6_HC: 0
day_7_HC: 0
peak_offpeak_percent: 0
monthly_evolution: 1.07
current_week_evolution: -100
current_month_evolution: -100
yesterday_evolution: 0
friendly_name: myelectricaldata_XXXX
errorLastCall: ''
errorLastCallInterne: ''
current_week_number: '01'
offpeak_hours_enedis: Lundi ();Mardi ();Mercredi ();Jeudi ();Vendredi ();Samedi ();Dimanche ();
offpeak_hours:
  - - - ''
  - - - ''
  - - - ''
  - - - ''
  - - - ''
  - - - ''
  - - - ''
subscribed_power: 6 kVA
unit_of_measurement: kWh
```

**Comment by Jib-san** [comment]
Pareil, depuis le début d'année j'ai la conso et le prix à 0. 
La version 0.8.13-beta1 n'a pas résolu le soucis.
Il semble y avoir un soucis avec le calcul HC/HP car les datas HP sont bien là. (j'ai pas de contrat HC/HP)

```yaml
numPDL: XXXXXXXXXXXXXXX
activationDate: 2021-02-23 00:00:00
lastUpdate: 2023-01-07 09:27:51
timeLastCall: 2023-01-07 09:27:51
yesterdayDate: 2023-01-06
yesterday: 0
yesterdayLastYearDate: 2022-01-07
yesterdayLastYear: 0
daily: 0, 0, 0, 0, 0, 0, 0
current_week: 0
last_week: 28.33
day_1: 0
day_2: 0
day_3: 0
day_4: 0
day_5: 0
day_6: 0
day_7: 0
current_week_last_year: 13.73
last_month: 133.19
current_month: 0
current_month_last_year: 11.81
last_month_last_year: 148.89
last_year: 1592.61
current_year: 0
current_year_last_year: 11.81
dailyweek: 2023-01-06, 2023-01-05, 2023-01-04, 2023-01-03, 2023-01-02, 2023-01-01, 2022-12-31
dailyweek_cost: 0, 0, 0, 0, 0, 0, 0
dailyweek_costHP: 0, 0, 0.3, 0.2, 0.3, 0.3, 0.3
dailyweek_HP: 0, 0, 1.5, 1.49, 1.55, 1.52, 1.54
daily_cost: 0
yesterday_HP_cost: 0
yesterday_HP: 0
day_1_HP: 0
day_2_HP: 0
day_3_HP: 1502
day_4_HP: 1490
day_5_HP: 1550
day_6_HP: 1527
day_7_HP: 1544
dailyweek_costHC: 0, 0, 0, 0, 0, 0, 0
dailyweek_HC: 0, 0, 0, 0, 0, 0, 0
yesterday_HC_cost: 0
yesterday_HC: 0
day_1_HC: 0
day_2_HC: 0
day_3_HC: 0
day_4_HC: 0
day_5_HC: 0
day_6_HC: 0
day_7_HC: 0
peak_offpeak_percent: 0
monthly_evolution: -10.55
current_week_evolution: -100
current_month_evolution: -100
yesterday_evolution: 0
friendly_name: myelectricaldata_XXXXXXXXXXXXXXX
errorLastCall: 
errorLastCallInterne: 
current_week_number: 01
offpeak_hours_enedis: Lundi ();Mardi ();Mercredi ();Jeudi ();Vendredi ();Samedi ();Dimanche ();
offpeak_hours: 
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''
- - - ''
subscribed_power: 6 kVA
unit_of_measurement: kWh
```


![myelecrticaldata_zero_issue_01](https://user-images.githubusercontent.com/13869992/211650640-aa093242-727b-468c-b432-151b737ef78f.jpg)
