### ISSUE TITLE
[BUG] - Exception export InfluxDB depuis 0.8.14

### ISSUE THREAD

**Issue by Mikayex** [m4dm4rtig4n/myelectricaldata#323]
J'ai l'exception suivante depuis la mise à jour en 0.8.14 lors de l'export des données dans InfluxDB :
```
Traceback (most recent call last):
  File "/app/models/jobs.py", line 228, in job_import_data
    ExportInfluxDB(self.usage_point_id).daily(
TypeError: daily() got an unexpected keyword argument 'price_hc'
```

Il semble que ce commit soit en cause : ef4b4b0b21e6d6cb86eed0b167da7382dbba4790

<details>
<summary>Configuration (si nécessaire)</summary>

```yaml
cycle: 14400
debug: false
home_assistant:
  discovery_prefix: homeassistant
  enable: false
influxdb:
  bucket: myelectricaldata
  enable: true
  hostname: influx
  method: batching
  org: home
  port: 8086
  token: #TOKEN#
mqtt:
  client_id: myelectricaldata
  enable: false
  hostname: X.X.X.X
  password: ''
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: ''
myelectricaldata:
  '#PDL#':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2023-03-20'
    consumption_max_date: '2023-03-20'
    consumption_max_power: 'true'
    consumption_price_base: '0.17757'
    consumption_price_hc: '0.15626'
    consumption_price_hp: '0.19541'
    enable: 'true'
    name: Maison
    offpeak_hours_0: 1H30-7H30;12H30-14H30
    offpeak_hours_1: 1H30-7H30;12H30-14H30
    offpeak_hours_2: 1H30-7H30;12H30-14H30
    offpeak_hours_3: 1H30-7H30;12H30-14H30
    offpeak_hours_4: 1H30-7H30;12H30-14H30
    offpeak_hours_5: 1H30-7H30;12H30-14H30
    offpeak_hours_6: 1H30-7H30;12H30-14H30
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: #TOKEN#

```
</details>

**Version : 0.8.14 (docker)**
